#1 Sprint 9
TatianaAV/java-filmorate pull request #1
Opened 2022-11-03 09:48 UTC by TatianaAV

2022-11-03 19:26 UTC, NikolaiDem requested changes

2022-11-03 19:26 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    protected int generatedId = 0;
private int generatedId = 0;
    private Manager valid = new Manager();

2022-11-03 19:26 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        valid.validationFilm(film);
Валидация уже есть на 52 строке.

2022-11-03 19:26 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +    Manager managerValidation = new Manager();
private

2022-11-03 19:26 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +    protected int generatedId = 0;
private

2022-11-03 19:26 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +    private final Logger log = LoggerFactory.getLogger(UserController.class);
А в FilmController-е используется @Slf4j. Лучше привести к единообразию)

2022-11-03 19:26 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/manager/Manager.java
> +
Лишняя пустая строка.

2022-11-03 19:26 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/manager/Manager.java
> +        if (film.getDescription().length() > 200) {
Надо проверить, и что description не null.

2022-11-03 19:26 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/manager/Manager.java
> +        if (film.getReleaseDate().isBefore(LocalDate.of(1895, 12, 28))) {
Надо проверить, и что releaseDate не null.

2022-11-03 19:26 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/manager/Manager.java
> +        if (user.getBirthday().isAfter(LocalDate.now())) {
Надо проверить, и что birthday не null.

2022-11-03 19:26 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/manager/Manager.java
> +        if (user.getName() == null) {
Надо проверить, и что name и не "".

2022-11-03 19:26 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +
Удалить лишние пустые строки.

2022-11-03 19:26 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +
Удалить лишние пустые строки.

2022-11-03 19:26 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +        return name.equals(film.name);
(Optional)
Почему уникальность объекта зависит от name, а не id?

2022-11-03 19:26 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +        return email.equals(user.email);
(Optional)
Почему уникальность объекта зависит от email, а не id?

2022-11-05 13:46 UTC, TatianaAV commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        valid.validationFilm(film);
Николай, но если вносят изменения и они не будут соответствовать условию валидации? При изменении данных, разве их не нужно проверять?

2022-11-05 14:54 UTC, TatianaAV commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +        return name.equals(film.name);
чтобы при добавлении нового пользователя сравнить уникальность только по email

2022-11-05 14:57 UTC, TatianaAV commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +        return email.equals(user.email);
при добавлении нового пользователя сравнить только email, так как если разные 
id и одинаковые  email, получатся разные пользователи

2022-11-05 15:01 UTC, TatianaAV commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +        return name.equals(film.name);
чтобы через поиск получить список всех фильмов с одинаковым названием :)

2022-11-05 15:27 UTC, TatianaAV commented on src/main/java/ru/yandex/practicum/filmorate/manager/Manager.java
> +        if (film.getDescription().length() > 200) {
я добавила, но мне кажется, что можно и без этой проверки, может же отсутствовать описание фильма. тогда нужно делать и минимум описания, а так точку поставил и всё, описание есть.

2022-11-06 09:56 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/manager/Manager.java
> +        if (film.getDescription().length() > 200) {
Все верно, тогда нужно изменить на
        if (film.getDescription() != null && film.getDescription().length() > 200) {}

2022-11-06 10:08 UTC, NikolaiDem approved these changes

2022-11-09 12:35 UTC, merged