sprint 10 ревью
TatianaAV/java-filmorate pull request #2
Opened 2022-11-17 21:56 UTC by TatianaAV

2022-11-18 20:37 UTC, NikolaiDem requested changes

2022-11-18 20:37 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        return filmStorage.findAll();
Лучше использовать методы сервиса вместо прямых вызовов методов хранилища. Например, потому что может понадобится изменить логику метода findAll(), и придется модифицировать контроллер. А у контроллера задача лишь маршрутизировать запрос в определенный метод сервиса, то есть логикой программы контроллер не занимается, потому и модифицироваться в данном случае он не должен.
Аналогично для остальных методов, напрямую обращающихся к хранилищу.

2022-11-18 20:37 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +        return userStorage.findAll();
Лучше использовать методы сервиса вместо прямых вызовов методов хранилища. Например, потому что может понадобится изменить логику метода findAll(), и придется модифицировать контроллер. А у контроллера задача лишь маршрутизировать запрос в определенный метод сервиса, то есть логикой программы контроллер не занимается, потому и модифицироваться в данном случае он не должен.
Аналогично для остальных методов, напрямую обращающихся к хранилищу.

2022-11-18 20:37 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +    private final InMemoryFilmStorage filmStorage;
Сервисы должны зависеть от интерфейсов классов-хранилищ, а не их реализаций. Таким образом при необходимости изменить реализацию хранилища сервис модифицироваться не будет.
Аналогично для InMemoryUserStorage.

2022-11-18 20:37 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +        if (!filmStorage.getFilms().containsKey(filmId)) {
Проверки 35-44 можно удалить, а 45-46 заменить на
        Film film = filmStorage.getFilmById(filmId);
        User user = userStorage.getUserById(userId);
Таким образом при отсутствии фильма или юзера исключение будет брошено в хранилищах.
Аналогично для удаления лайка.

2022-11-18 20:37 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +        filmStorage.getFilms().put(filmId, film);
Лучше вызвать метод обновления фильма updateFilm(...)
Аналогично для удаления лайка.

2022-11-18 20:37 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +        film.getLikes().add(user.getId());
Лучше добавить метод добавления лайка в класс Film (addLike(...))
Аналогично для удаления лайка.

2022-11-18 20:37 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +    protected TreeSet<Film> popularFilm =
Управлением данных занимается хранилище, поэтому хранить их в сервисе не нужно)

2022-11-18 20:37 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/user/UserService.java
> +    private final InMemoryUserStorage userStorage;
Сервисы должны зависеть от интерфейсов классов-хранилищ, а не их реализаций. Таким образом при необходимости изменить реализацию хранилища сервис модифицироваться не будет.

2022-11-18 20:37 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/user/UserService.java
> +            if (userStorage.getUsers().containsKey(id)) {
Можно сразу добавить friends.add(userStorage.getUserById(id));
И сделать это через стрим.

2022-11-18 20:37 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/user/UserService.java
> +        if (!userStorage.getUsers().containsKey(userId) || !userStorage.getUsers().containsKey(friendId)) {
Проверку можно убрать и юзеров находить с помощью методов getUserById(...) (в них будет исключение, если юзеры не найдены)
Аналогично для метода добавления друзей.

2022-11-18 20:37 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/user/UserService.java
> +        user.getFriends().removeIf(id -> friendId == user.getId());
При удалении можно вызвать только remove(...) (у сетов нет методов удаления по индексу)
Аналогично для метода добавления друзей.

2022-11-18 20:37 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/user/UserService.java
> +        userStorage.getUsers().put(id, user);
Лучше заменить на метод обновления юзера.

2022-11-18 20:37 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/user/UserService.java
> +        userStorage.getUsers().put(friendId, friend);
Лучше заменить на метод обновления юзера.

2022-11-18 20:37 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/user/UserService.java
> +        User user = userStorage.getUsers().get(userId);
Юзеров лучше получать методом getUserById(...)

2022-11-18 20:37 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmStorage.java
> +public interface FilmStorage {
Разделить методы пустой строкой.

2022-11-18 20:37 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +    public HashMap<Long, Film> getFilms() {
По код стайлу сначала должны идти поля класса, а потом методы)

2022-11-18 20:37 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +    public HashMap<Long, User> getUsers() {
По код стайлу сначала должны идти поля класса, а потом методы)

2022-11-18 20:37 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +            //long duration автоматически подставляет 0, всё равно проверять на null?
Не нужно)

2022-11-18 20:37 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        return films.remove(film.getId(), film);
Достаточно использовать удаление по id films.remove(film.getId())

2022-11-18 20:37 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +       users.remove(user.getId(), user);
Достаточно использовать удаление по id users.remove(user.getId())

2022-11-19 18:20 UTC, TatianaAV commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        return filmStorage.findAll();
Спасибо за разъяснение. На вебинаре сказали, что не принципиально, куда будет обращаться метод к хранилищу или к сервису.

2022-11-19 22:24 UTC, TatianaAV commented on src/main/java/ru/yandex/practicum/filmorate/service/user/UserService.java
> +        if (!userStorage.getUsers().containsKey(userId) || !userStorage.getUsers().containsKey(friendId)) {
Думала, что дальше будем считать историю просмотра по этим методам

2022-11-19 23:26 UTC, TatianaAV commented
Добрый день. отправила, а потом увидела в комментарии стрим. пыталась добавить в старый коммит изменения, но не получилось. Извините

2022-11-20 09:57 UTC, NikolaiDem approved these changes

2022-11-20 10:01 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/user/UserService.java
> +        for (long id : user.getFriends()) {
Тоже можно сделать через стрим.

2022-11-23 13:03 UTC, TatianaAV commented on src/main/java/ru/yandex/practicum/filmorate/service/user/UserService.java
> +        for (long id : user.getFriends()) {
сделала. не понимаю как этот у меня получается, но получается 😁. волшебство эти стримы

2022-11-25 17:35 UTC, merged