Add database
TatianaAV/java-filmorate pull request #3
Opened 2022-12-17 20:52 UTC by TatianaAV

2022-12-19 07:48 UTC, NikolaiDem requested changes
Татьяна, просьба применить форматирование по CodeStyle ко всем файлам.

2022-12-19 07:48 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controllers/ErrorHandler.java
> +    @ExceptionHandler
Одинаковые обработки исключений можно объединить в один метод. Для этого можно указать типы исключений, обрабатываемых в методе. Например,
@ExceptionHandler({FilmNotFoundException.class, ObjectNotFoundException.class})
Аналогично для BAD_REQUEST

2022-12-19 07:48 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    @GetMapping("/genres/{id}")
Эндпоинты для mpa и genre лучше вынести в соответствующие контроллеры MpaController и GenreController.

2022-12-19 07:48 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    public Optional<Film> getFilmById(@PathVariable("id") long filmId) {
Optional здесь лишний.

2022-12-19 07:48 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +    public Optional<User> getUserById(@PathVariable("id") Long userId) {
Optional здесь лишний.

2022-12-19 07:48 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    public String toString() {
Можно использовать lombok:
@ToString

2022-12-19 07:48 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @Id
Для чего добавлен @Id?)

2022-12-19 07:48 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/model/Genre.java
> +   private String name;
CodeStyle : выровнять отступы.

2022-12-19 07:48 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/model/MPA.java
> +        this.id=mpaId;
CodeStyle : this.id = mpaId;

2022-12-19 07:48 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    public String toString() {
Лучше использовать lombok :
@ToString

2022-12-19 07:48 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +    public MPA getByIdMpa(int id) {
Методы для mpa и genre лучше вынести в соответствующие сервисы.

2022-12-19 07:48 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmStorage.java
> +        // выполняем запрос к базе данных.
Удалить закомментированный код.

2022-12-19 07:48 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/FriendStorage.java
> +
Удалить лишние пустые строки.

2022-12-19 07:48 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/DbFilmStorage.java
> +        if (genres.size() == 0 && row < 1) {
Для чего условие row < 1 ?

2022-12-19 07:48 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/DbFilmStorage.java
> +        int row = jdbcTemplate.update("delete from FILM_MPA where FILM_ID = ?", film.getId());
FILM_MPA - избыточная таблица, mpa_id можно хранить непосредственно в таблице films, потому что отношения между film и mpa 1:1.

2022-12-19 07:48 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/DbFilmStorage.java
> +        String sql = "select * from FILMS group by FILM_ID, RATE  order by  max(RATE) desc limit ?";
Для чего здесь group by, почему max(RATE), а не RATE?

2022-12-19 07:48 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/DbFilmStorage.java
> +        if (getGenresFilm(film.getId()).size() > 1 || !getGenresFilm(film.getId()).isEmpty()) {
Лучше сделать добавление жанров отдельным методом. Для того, чтобы иметь возможность сразу вытащить все жанры для списка фильмов, а не для каждого в отдельности (чтобы избежать проблемы N+1).

2022-12-19 07:48 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/DbFriendStorage.java
> +        if(row < 1)
CodeStyle :  if (row < 1) {
            throw new UserNotFoundException("удалено {} строк = " + row);
        }
Аналогично для остальных методов.

2022-12-19 07:48 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/DbFriendStorage.java
> +                "WHERE USER_ID IN (SELECT f1.friend_id " +
Попробовать сделать без вложенного запроса, а с помощью джойнов.

2022-12-19 07:48 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/model/Genre.java
> +    public Genre(int id) {
Не используется.

2022-12-19 07:48 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/model/MPA.java
> +    public MPA(int mpaId) {
Не используется.

2022-12-19 07:48 UTC, NikolaiDem commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +class FilmoRateApplicationTests {
Название класса не совпадает с названием java файла.

2022-12-19 07:48 UTC, NikolaiDem commented on src/test/java/ru/yandex/practicum/filmorate/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS users (
Для тестов лучше использовать схему продакшена, иначе они живут в параллельном мире)

2022-12-19 07:48 UTC, NikolaiDem commented on src/test/java/ru/yandex/practicum/filmorate/controllers/UserControllerValidationTest.java
> +   /* @Test
Удалить закомментированный код.

2022-12-19 07:48 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/DbUserStorage.java
> +        SqlRowSet userRows = jdbcTemplate.queryForRowSet("select * from users where USER_ID = ?", id);
Можно избавиться от дублирования (при создании пользователя) :    
   User user = jdbcTemplate.query("select * from users where USER_ID = ?", DbUserStorage::makeUser, id);

2022-12-19 07:48 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/DbGenreStorage.java
> +        return jdbcTemplate.queryForObject(sql, DbGenreStorage::makeGenre, genreId);
Лучше избавиться от повторного запроса к БД (первый в 33 строке, второй в 38). Можно использовать jdbcTemplate.query(...)

2022-12-19 18:27 UTC, TatianaAV commented on src/main/java/ru/yandex/practicum/filmorate/controllers/ErrorHandler.java
> +    @ExceptionHandler
Спасибо, искала такое, но самостоятельно не нашла

2022-12-20 11:07 UTC, TatianaAV commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/DbFilmStorage.java
> +                jdbcTemplate.query(sql, (rs, rowNum) -> makeFilm(rs), filmId);
вот makeFilm делает для списка фильмов

2022-12-22 00:21 UTC, NikolaiDem requested changes

2022-12-22 00:21 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controllers/ErrorHandler.java
> +    @ExceptionHandler({SQLException.class, DataAccessException.class, Throwable.class})
spring перехватит только проверяемые исключения (наследники Exception), поэтому Throwable можно сократить до Exception. Exception и SQLException (DataAccessException) являются исключениями разного "уровня", поэтому Exception лучше обработать в отдельном методе.

2022-12-22 00:21 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +           Film film) {
CodeStyle - перенести на одну строку.

2022-12-22 00:21 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    create(@RequestBody
(Optional)
Для избавления от ручной валидации можно добавить аннотацию @Valid к аргументу Film, а в Film к полям добавить соответствующие аннотации (@NotNull, @NotBlank, @Size, @Min и т.д.). Тогда валидация будет выполняться spring-ом перед вызовом метода контроллера.
Аналогично для остальных контроллеров.

2022-12-22 00:21 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controllers/GenresControllers.java
> +public class GenresControllers {
Контроллер все же один) GenresController

2022-12-22 00:21 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +    @PostMapping()
@PostMapping

2022-12-22 00:21 UTC, NikolaiDem commented on pom.xml
> +        <dependency>
Пока что зависимость лишняя)

2022-12-22 00:21 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/genres/GenresService.java
> +
Лишняя пустая строка.

2022-12-22 00:21 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/mpa/MpaService.java
> +
Лишняя пустая строка.

2022-12-22 00:21 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/user/UserService.java
> +
Лишняя пустая строка.

2022-12-22 00:21 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/DbFilmStorage.java
> +        if (film.getGenres() == null || film.getGenres().isEmpty()
Зачем проверка film.getGenres().size() < 1), если перед этим проверка film.getGenres().isEmpty() ? И достаточно проверки только на null.

2022-12-22 00:21 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/DbFilmStorage.java
> +        genres.addAll(film.getGenres());
Сначала в film устанавливаются жанры из genres, потом в genres устанавливаются жанры из film. Лучше сделать одну прямую ветвь. Убрать предыдущую проверку и сделать так, чтобы film.getGenres() никогда не возвращал null.

2022-12-22 00:21 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/DbFilmStorage.java
> +                resultSet.getInt("rate")
rate обновлять не нужно, ведь извне может прийти любое значение, а rate вычисляется автоматически.

2022-12-22 00:21 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/DbFilmStorage.java
> +                "     group by FILM_ID, RATE  order by RATE desc limit ?";
Зачем здесь group by, ведь никакие аналитические функции к полям не применяются)

2022-12-22 00:21 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/DbFilmStorage.java
> +        if (getGenresFilm(film.getId()).size() > 1 || !getGenresFilm(film.getId()).isEmpty()) {
Здесь возникает проблема "N+1 query". Одним запросом получены все N фильмов, и для каждого фильма нужно сделать еще по одному запросу (на получение жанров), то есть дополнительных N запросов. Как вариант снизить количество дополнительных запросов до одного - использовать
void query(String sql, RowCallbackHandler rch, @Nullable Object... args)
Где sql - запрос на получение всех жанров (то есть такая сджойненная таблица : filmId, genreId, genreName).  Пройти по всем строкам такой сджойненной таблицы, и для каждой строки сконструировать жанр и добавить его в соответствующий фильм. Для этого установку жанров лучше вынести в отдельный метод.

2022-12-22 00:21 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/DbUserStorage.java
> +    public static User makeUser(ResultSet userRows) throws SQLException {
private

2022-12-22 15:30 UTC, TatianaAV commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    create(@RequestBody
Да, я пробовала, все работает с аннотациями. с моим вариантом отладка проще (для меня) :)

2022-12-22 16:09 UTC, TatianaAV commented on pom.xml
> +        <dependency>
без нее не работает аннотация @Slf4j

2022-12-22 21:16 UTC, TatianaAV commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/DbFilmStorage.java
> +        if (getGenresFilm(film.getId()).size() > 1 || !getGenresFilm(film.getId()).isEmpty()) {
То есть за один раз обращаться к базе данных с запросом на создание фильмов и получать сразу все поля и список жанров? Боюсь не смогу, недостаточно теории для формирования запросов. Её совсем не дали в этом курсе. И наставник ничего не показывает, только на словах обьясняет.

2022-12-22 22:48 UTC, NikolaiDem commented on pom.xml
> +        <dependency>
@slf4j ломбоковская, а я имел ввиду spring-boot-starter-data-jpa )

2022-12-22 23:07 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/DbFilmStorage.java
> +        if (getGenresFilm(film.getId()).size() > 1 || !getGenresFilm(film.getId()).isEmpty()) {
1) Нам нужно получить запрос для поиска жанров для списка фильмов.
Для одного фильма запрос таков:
"select FILM_ID, G.GENRE_ID, G.NAME from GENRE G " +
                        "left join FILM_GENRE FG on G.GENRE_ID = FG.GENRE_ID " +
                        "where FILM_ID = ?"
Такой запрос вернет что-нибудь наподобие :
FILM_ID, G.GENRE_ID, G.NAME
1             1                   Драма

А нужно для списка фильмов, например
FILM_ID, G.GENRE_ID, G.NAME
1             1                   Драма
2             4                   Комедия
3             4                   Комедия
Для формирования такого запроса нужно воспользоваться условием "where FILM_ID in (список фильм id) "
2) Получили список фильмов с жанрами, например,
1             1                   Драма
2             4                   Комедия
3             4                   Комедия
Теперь используем метод JdbcTemplate
public void query(String sql, RowCallbackHandler rch, @Nullable Object... args) throws DataAccessException {
    this.query(sql, this.newArgPreparedStatementSetter(args), rch);
  }
Здесь в качестве RowCallbackHandler - обработчик каждой строки из ответа. То есть должны описать, что делать с каждой строкой. Например, обрабатываем первую строку 
1             1                   Драма
Сразу можем сделать объект жанра (new Genre(...)). И нам надо этот жанр добавить в соответствующий фильм. Как найти фильм ? А фильмы у нас приходят в метод saveGenres(...) Нам надо только из списка(мапы) фильмов найти нужный фильм и добавить в него этот жанр.

2022-12-23 11:35 UTC, TatianaAV commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/DbFilmStorage.java
> +        if (getGenresFilm(film.getId()).size() > 1 || !getGenresFilm(film.getId()).isEmpty()) {
спасибо. я нашла в комментариях чата ссылку от куратора.   https://www.baeldung.com/spring-jdbctemplate-in-list
подходит такая реализация?

2022-12-23 22:19 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/DbFilmStorage.java
> +        if (getGenresFilm(film.getId()).size() > 1 || !getGenresFilm(film.getId()).isEmpty()) {
Верно

2022-12-23 22:19 UTC, NikolaiDem approved these changes

2022-12-23 22:56 UTC, merged